fix compilation issue on ubuntu 22.04
In file included from /usr/include/x86_64-linux-gnu/urcu/pointer.h:39,
                 from /usr/include/x86_64-linux-gnu/urcu/urcu-qsbr.h:40,
                 from /usr/include/x86_64-linux-gnu/urcu-qsbr.h:2,
                 from libgdmaps/gdmaps.c:52:
libgdmaps/gdmaps.c: In function 'gdmap_lookup':
libgdmaps/gdmaps.c:468:36: error: invalid use of undefined type 'struct dclists'
  468                                     rcu_dereference(gdmap->dclists),
                                          ^~~~~~~~~~~~~~~
make[3]: *** [Makefile:1212: libgdmaps/gdmaps.o] Error 1

The patch moves the struct dclists definition in dclists.h so the
compiler is happy with the typedef.

Fix #220.